const imageMap: Record<string, { image0: string; image1: string; credit: string }> = {
  ex_bankdruecken: { image0: "ex_bankdruecken/0.jpg", image1: "ex_bankdruecken/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_schraegbank: { image0: "ex_schraegbank/0.jpg", image1: "ex_schraegbank/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_fliegende: { image0: "ex_fliegende/0.jpg", image1: "ex_fliegende/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_dips: { image0: "ex_dips/0.jpg", image1: "ex_dips/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_liegestuetze: { image0: "ex_liegestuetze/0.jpg", image1: "ex_liegestuetze/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_schulterdruecken: { image0: "ex_schulterdruecken/0.jpg", image1: "ex_schulterdruecken/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_military_press: { image0: "ex_military_press/0.jpg", image1: "ex_military_press/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_seitheben: { image0: "ex_seitheben/0.jpg", image1: "ex_seitheben/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_frontheben: { image0: "ex_frontheben/0.jpg", image1: "ex_frontheben/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_overhead_triceps: { image0: "ex_overhead_triceps/0.jpg", image1: "ex_overhead_triceps/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_close_grip_bench: { image0: "ex_close_grip_bench/0.jpg", image1: "ex_close_grip_bench/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_klimmzuege: { image0: "ex_klimmzuege/0.jpg", image1: "ex_klimmzuege/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_lh: { image0: "ex_rudern_lh/0.jpg", image1: "ex_rudern_lh/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_einarm_rudern: { image0: "ex_einarm_rudern/0.jpg", image1: "ex_einarm_rudern/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kreuzheben: { image0: "ex_kreuzheben/0.jpg", image1: "ex_kreuzheben/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rdl: { image0: "ex_rdl/0.jpg", image1: "ex_rdl/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_shrugs: { image0: "ex_shrugs/0.jpg", image1: "ex_shrugs/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_bizepscurls: { image0: "ex_bizepscurls/0.jpg", image1: "ex_bizepscurls/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_hammer_curls: { image0: "ex_hammer_curls/0.jpg", image1: "ex_hammer_curls/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_sz_curls: { image0: "ex_sz_curls/0.jpg", image1: "ex_sz_curls/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kniebeugen: { image0: "ex_kniebeugen/0.jpg", image1: "ex_kniebeugen/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_frontkniebeugen: { image0: "ex_frontkniebeugen/0.jpg", image1: "ex_frontkniebeugen/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_goblet: { image0: "ex_goblet/0.jpg", image1: "ex_goblet/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_ausfallschritte: { image0: "ex_ausfallschritte/0.jpg", image1: "ex_ausfallschritte/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_bulgarisch: { image0: "ex_bulgarisch/0.jpg", image1: "ex_bulgarisch/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_hip_thrust: { image0: "ex_hip_thrust/0.jpg", image1: "ex_hip_thrust/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_plank: { image0: "ex_plank/0.jpg", image1: "ex_plank/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_crunches: { image0: "ex_crunches/0.jpg", image1: "ex_crunches/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_hanging_raises: { image0: "ex_hanging_raises/0.jpg", image1: "ex_hanging_raises/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_russian_twist: { image0: "ex_russian_twist/0.jpg", image1: "ex_russian_twist/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_ab_wheel: { image0: "ex_ab_wheel/0.jpg", image1: "ex_ab_wheel/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_seilspringen: { image0: "ex_seilspringen/0.jpg", image1: "ex_seilspringen/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabelueberzuege: { image0: "ex_kabelueberzuege/0.jpg", image1: "ex_kabelueberzuege/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_fliegend_hoch: { image0: "ex_kabel_fliegend_hoch/0.jpg", image1: "ex_kabel_fliegend_hoch/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_fliegend_mittel: { image0: "ex_kabel_fliegend_mittel/0.jpg", image1: "ex_kabel_fliegend_mittel/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_fliegend_tief: { image0: "ex_kabel_fliegend_tief/0.jpg", image1: "ex_kabel_fliegend_tief/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_crossover: { image0: "ex_kabel_crossover/0.jpg", image1: "ex_kabel_crossover/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_fliegend_einarmig: { image0: "ex_kabel_fliegend_einarmig/0.jpg", image1: "ex_kabel_fliegend_einarmig/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_brustpresse: { image0: "ex_kabel_brustpresse/0.jpg", image1: "ex_kabel_brustpresse/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_fliegend_schraeg: { image0: "ex_kabel_fliegend_schraeg/0.jpg", image1: "ex_kabel_fliegend_schraeg/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_brustpresse: { image0: "ex_brustpresse/0.jpg", image1: "ex_brustpresse/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_brustpresse_schraeg: { image0: "ex_brustpresse_schraeg/0.jpg", image1: "ex_brustpresse_schraeg/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_brustpresse_konvergent: { image0: "ex_brustpresse_konvergent/0.jpg", image1: "ex_brustpresse_konvergent/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_pec_deck: { image0: "ex_pec_deck/0.jpg", image1: "ex_pec_deck/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_pec_deck_reverse: { image0: "ex_pec_deck_reverse/0.jpg", image1: "ex_pec_deck_reverse/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_kabel: { image0: "ex_rudern_kabel/0.jpg", image1: "ex_rudern_kabel/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_latzug: { image0: "ex_latzug/0.jpg", image1: "ex_latzug/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_latzug_eng: { image0: "ex_latzug_eng/0.jpg", image1: "ex_latzug_eng/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_latzug_neutral: { image0: "ex_latzug_neutral/0.jpg", image1: "ex_latzug_neutral/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_latzug_supiniert: { image0: "ex_latzug_supiniert/0.jpg", image1: "ex_latzug_supiniert/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_latzug_einarmig: { image0: "ex_latzug_einarmig/0.jpg", image1: "ex_latzug_einarmig/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_kabel_eng: { image0: "ex_rudern_kabel_eng/0.jpg", image1: "ex_rudern_kabel_eng/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_kabel_breit: { image0: "ex_rudern_kabel_breit/0.jpg", image1: "ex_rudern_kabel_breit/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_kabel_neutral: { image0: "ex_rudern_kabel_neutral/0.jpg", image1: "ex_rudern_kabel_neutral/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_kabel_einarmig: { image0: "ex_rudern_kabel_einarmig/0.jpg", image1: "ex_rudern_kabel_einarmig/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_straight_arm_pulldown: { image0: "ex_straight_arm_pulldown/0.jpg", image1: "ex_straight_arm_pulldown/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_pullover: { image0: "ex_kabel_pullover/0.jpg", image1: "ex_kabel_pullover/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_face_pulls: { image0: "ex_face_pulls/0.jpg", image1: "ex_face_pulls/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_face_pulls_einarmig: { image0: "ex_face_pulls_einarmig/0.jpg", image1: "ex_face_pulls_einarmig/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_shrugs: { image0: "ex_kabel_shrugs/0.jpg", image1: "ex_kabel_shrugs/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_maschine: { image0: "ex_rudern_maschine/0.jpg", image1: "ex_rudern_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_maschine_einarmig: { image0: "ex_rudern_maschine_einarmig/0.jpg", image1: "ex_rudern_maschine_einarmig/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_brustgestuetzt: { image0: "ex_rudern_brustgestuetzt/0.jpg", image1: "ex_rudern_brustgestuetzt/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_tbar: { image0: "ex_rudern_tbar/0.jpg", image1: "ex_rudern_tbar/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_high_row: { image0: "ex_high_row/0.jpg", image1: "ex_high_row/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_low_row: { image0: "ex_low_row/0.jpg", image1: "ex_low_row/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_latzug_maschine: { image0: "ex_latzug_maschine/0.jpg", image1: "ex_latzug_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_face_pulls_seil: { image0: "ex_face_pulls_seil/0.jpg", image1: "ex_face_pulls_seil/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_seitheben: { image0: "ex_kabel_seitheben/0.jpg", image1: "ex_kabel_seitheben/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_seitheben_einarmig: { image0: "ex_kabel_seitheben_einarmig/0.jpg", image1: "ex_kabel_seitheben_einarmig/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_seitheben_hinten: { image0: "ex_kabel_seitheben_hinten/0.jpg", image1: "ex_kabel_seitheben_hinten/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_frontheben: { image0: "ex_kabel_frontheben/0.jpg", image1: "ex_kabel_frontheben/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_reverse_fly: { image0: "ex_kabel_reverse_fly/0.jpg", image1: "ex_kabel_reverse_fly/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_y_raise: { image0: "ex_kabel_y_raise/0.jpg", image1: "ex_kabel_y_raise/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_upright_row: { image0: "ex_kabel_upright_row/0.jpg", image1: "ex_kabel_upright_row/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_trizepsdruecken: { image0: "ex_trizepsdruecken/0.jpg", image1: "ex_trizepsdruecken/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_schulterpresse_maschine: { image0: "ex_schulterpresse_maschine/0.jpg", image1: "ex_schulterpresse_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_schulterpresse_konvergent: { image0: "ex_schulterpresse_konvergent/0.jpg", image1: "ex_schulterpresse_konvergent/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_seitheben_maschine: { image0: "ex_seitheben_maschine/0.jpg", image1: "ex_seitheben_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_reverse_fly_maschine: { image0: "ex_reverse_fly_maschine/0.jpg", image1: "ex_reverse_fly_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinpresse: { image0: "ex_beinpresse/0.jpg", image1: "ex_beinpresse/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinpresse_horizontal: { image0: "ex_beinpresse_horizontal/0.jpg", image1: "ex_beinpresse_horizontal/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinpresse_vertikal: { image0: "ex_beinpresse_vertikal/0.jpg", image1: "ex_beinpresse_vertikal/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinpresse_einbein: { image0: "ex_beinpresse_einbein/0.jpg", image1: "ex_beinpresse_einbein/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinstrecker: { image0: "ex_beinstrecker/0.jpg", image1: "ex_beinstrecker/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinstrecker_einbein: { image0: "ex_beinstrecker_einbein/0.jpg", image1: "ex_beinstrecker_einbein/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_hack_squat: { image0: "ex_hack_squat/0.jpg", image1: "ex_hack_squat/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_pendulum_squat: { image0: "ex_pendulum_squat/0.jpg", image1: "ex_pendulum_squat/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_belt_squat: { image0: "ex_belt_squat/0.jpg", image1: "ex_belt_squat/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_smith_kniebeuge: { image0: "ex_smith_kniebeuge/0.jpg", image1: "ex_smith_kniebeuge/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_sissy_squat_maschine: { image0: "ex_sissy_squat_maschine/0.jpg", image1: "ex_sissy_squat_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinbeuger: { image0: "ex_beinbeuger/0.jpg", image1: "ex_beinbeuger/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinbeuger_liegend: { image0: "ex_beinbeuger_liegend/0.jpg", image1: "ex_beinbeuger_liegend/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinbeuger_sitzend: { image0: "ex_beinbeuger_sitzend/0.jpg", image1: "ex_beinbeuger_sitzend/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinbeuger_stehend: { image0: "ex_beinbeuger_stehend/0.jpg", image1: "ex_beinbeuger_stehend/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_beinbeuger_einbein: { image0: "ex_beinbeuger_einbein/0.jpg", image1: "ex_beinbeuger_einbein/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_glute_drive: { image0: "ex_glute_drive/0.jpg", image1: "ex_glute_drive/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_hip_thrust_maschine: { image0: "ex_hip_thrust_maschine/0.jpg", image1: "ex_hip_thrust_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kickback_maschine: { image0: "ex_kickback_maschine/0.jpg", image1: "ex_kickback_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_abduktoren: { image0: "ex_abduktoren/0.jpg", image1: "ex_abduktoren/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_adduktoren: { image0: "ex_adduktoren/0.jpg", image1: "ex_adduktoren/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_kickback: { image0: "ex_kabel_kickback/0.jpg", image1: "ex_kabel_kickback/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_pullthrough: { image0: "ex_kabel_pullthrough/0.jpg", image1: "ex_kabel_pullthrough/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_good_morning: { image0: "ex_kabel_good_morning/0.jpg", image1: "ex_kabel_good_morning/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_wadenheben: { image0: "ex_wadenheben/0.jpg", image1: "ex_wadenheben/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_wadenheben_sitzend: { image0: "ex_wadenheben_sitzend/0.jpg", image1: "ex_wadenheben_sitzend/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_wadenheben_beinpresse: { image0: "ex_wadenheben_beinpresse/0.jpg", image1: "ex_wadenheben_beinpresse/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_wadenheben_einbein: { image0: "ex_wadenheben_einbein/0.jpg", image1: "ex_wadenheben_einbein/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_trizeps_seil: { image0: "ex_trizeps_seil/0.jpg", image1: "ex_trizeps_seil/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_trizeps_stange: { image0: "ex_trizeps_stange/0.jpg", image1: "ex_trizeps_stange/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_trizeps_einhand: { image0: "ex_trizeps_einhand/0.jpg", image1: "ex_trizeps_einhand/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_trizeps_ueberkopf_seil: { image0: "ex_trizeps_ueberkopf_seil/0.jpg", image1: "ex_trizeps_ueberkopf_seil/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_trizeps_kickback_kabel: { image0: "ex_trizeps_kickback_kabel/0.jpg", image1: "ex_trizeps_kickback_kabel/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_trizeps_pushdown_einarmig: { image0: "ex_trizeps_pushdown_einarmig/0.jpg", image1: "ex_trizeps_pushdown_einarmig/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_trizepsmaschine: { image0: "ex_trizepsmaschine/0.jpg", image1: "ex_trizepsmaschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabelcurl_stange: { image0: "ex_kabelcurl_stange/0.jpg", image1: "ex_kabelcurl_stange/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabelcurl_ez: { image0: "ex_kabelcurl_ez/0.jpg", image1: "ex_kabelcurl_ez/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabelcurl_seil: { image0: "ex_kabelcurl_seil/0.jpg", image1: "ex_kabelcurl_seil/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabelcurl_tief: { image0: "ex_kabelcurl_tief/0.jpg", image1: "ex_kabelcurl_tief/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabelcurl_hoch: { image0: "ex_kabelcurl_hoch/0.jpg", image1: "ex_kabelcurl_hoch/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabelcurl_einarmig: { image0: "ex_kabelcurl_einarmig/0.jpg", image1: "ex_kabelcurl_einarmig/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_bayesian_curl: { image0: "ex_bayesian_curl/0.jpg", image1: "ex_bayesian_curl/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_crossbody_curl: { image0: "ex_kabel_crossbody_curl/0.jpg", image1: "ex_kabel_crossbody_curl/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_bizepsmaschine: { image0: "ex_bizepsmaschine/0.jpg", image1: "ex_bizepsmaschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_preacher_curl_maschine: { image0: "ex_preacher_curl_maschine/0.jpg", image1: "ex_preacher_curl_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_crunch: { image0: "ex_kabel_crunch/0.jpg", image1: "ex_kabel_crunch/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_rotation: { image0: "ex_kabel_rotation/0.jpg", image1: "ex_kabel_rotation/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_rotation_kniend: { image0: "ex_kabel_rotation_kniend/0.jpg", image1: "ex_kabel_rotation_kniend/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_woodchopper_oben: { image0: "ex_woodchopper_oben/0.jpg", image1: "ex_woodchopper_oben/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_woodchopper_unten: { image0: "ex_woodchopper_unten/0.jpg", image1: "ex_woodchopper_unten/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_pallof_kniend: { image0: "ex_pallof_kniend/0.jpg", image1: "ex_pallof_kniend/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_seitcrunch: { image0: "ex_kabel_seitcrunch/0.jpg", image1: "ex_kabel_seitcrunch/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_kabel_hueftheben: { image0: "ex_kabel_hueftheben/0.jpg", image1: "ex_kabel_hueftheben/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_pallof: { image0: "ex_pallof/0.jpg", image1: "ex_pallof/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_crunch_maschine: { image0: "ex_crunch_maschine/0.jpg", image1: "ex_crunch_maschine/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rueckenstrecker: { image0: "ex_rueckenstrecker/0.jpg", image1: "ex_rueckenstrecker/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_laufband: { image0: "ex_laufband/0.jpg", image1: "ex_laufband/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_rudern_cardio: { image0: "ex_rudern_cardio/0.jpg", image1: "ex_rudern_cardio/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_fahrrad: { image0: "ex_fahrrad/0.jpg", image1: "ex_fahrrad/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_stairmaster: { image0: "ex_stairmaster/0.jpg", image1: "ex_stairmaster/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_ellips_trainer: { image0: "ex_ellips_trainer/0.jpg", image1: "ex_ellips_trainer/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_airbike: { image0: "ex_airbike/0.jpg", image1: "ex_airbike/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_ski_erg: { image0: "ex_ski_erg/0.jpg", image1: "ex_ski_erg/1.jpg", credit: "Free Exercise DB (Public Domain)" },
  ex_assault_bike: { image0: "ex_assault_bike/0.jpg", image1: "ex_assault_bike/1.jpg", credit: "Free Exercise DB (Public Domain)" },
};

const aliasMap: Record<string, string> = {
};

const IMAGE_BASE = "/exercises/";

function resolveImageEntry(id: string): { image0: string; image1: string; credit: string } | null {
  if (id in imageMap) return imageMap[id];
  const alias = aliasMap[id];
  if (alias && alias in imageMap) return imageMap[alias];
  return null;
}

export function getExerciseImage(id: string): { src0: string; src1: string; credit: string } | null {
  const entry = resolveImageEntry(id);
  if (!entry) return null;
  return {
    src0: `${IMAGE_BASE}${entry.image0}`,
    src1: `${IMAGE_BASE}${entry.image1}`,
    credit: entry.credit,
  };
}

export function getExerciseThumbnail(id: string): string | null {
  const entry = resolveImageEntry(id);
  if (!entry) return null;
  return `${IMAGE_BASE}${entry.image0}`;
}
